name: Tests

on:
  push:
    branches:
      - devel
  pull_request:

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: ['2.0.0', 'stable', 'devel']
      fail-fast: false
      max-parallel: 3

    name: Nim ${{ matrix.nim }}
    steps:
    - name: Setup Nim Enviroment
      uses: actions/checkout@v4

    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update nimble
      run: nimble update

    - name: Run tests
      run: nimble test

    - name: Test doc examples
      run: nimble doc src/jaysonrpc.nim

  deploy:
    needs: test
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/devel'
    steps:
      - uses: actions/checkout@v4

      - name: "Setup nim"
        uses: jiro4989/setup-nim-action@v1

      - name: "Build documentation"
        uses: ire4ever1190/nim-docs-action@v1
        with:
          main-file: "src/jaysonrpc.nim"
          deploy: "pages"
